kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-jenkins
  namespace: jenkins
  labels:
    "app.kubernetes.io/name": 'jenkins'
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: {{ .Values.jenkins.storage.size | quote }}