apiVersion: v1
kind: Service
metadata:
  name: my-jenkins
  namespace: jenkins
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    "app.kubernetes.io/component": "jenkins-controller"
    "app.kubernetes.io/instance": "my-jenkins"
  type: ClusterIP