apiVersion: v1
kind: Service
metadata:
  name: my-jenkins-agent
  namespace: jenkins
spec:
  ports:
    - port: 50000
      targetPort: 50000
      name: agent-listener
  selector:
    "app.kubernetes.io/component": "jenkins-controller"
    "app.kubernetes.io/instance": "my-jenkins"
  type: ClusterIP