apiVersion: v1
kind: Secret
metadata:
  name: my-jenkins
  namespace: jenkins
  labels:
    "app.kubernetes.io/name": 'jenkins'
    "helm.sh/chart": "jenkins-5.8.5"
    "app.kubernetes.io/managed-by": "Helm"
    "app.kubernetes.io/instance": "my-jenkins"
    "app.kubernetes.io/component": "jenkins-controller"
type: Opaque
data:
  jenkins-admin-password: {{ .Values.jenkins.adminPassword | b64enc | quote }}
  jenkins-admin-user: {{ .Values.jenkins.adminUser | b64enc | quote }}