apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: my-jenkins
  namespace: jenkins
  labels:
    "app.kubernetes.io/name": 'jenkins'
    "helm.sh/chart": "jenkins-5.8.5"
    "app.kubernetes.io/managed-by": "Helm"
    "app.kubernetes.io/instance": "my-jenkins"
    "app.kubernetes.io/component": "jenkins-controller"